cask_args appdir: '/Applications'
tap 'homebrew/bundle'
tap 'homebrew/services'
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'd12frosted/emacs-plus'

cask 'java'

brew 'ack'
brew 'autoconf'
brew 'awscli'
brew 'readline'
brew 'bash'
brew 'bash-completion'
brew 'chromedriver'
brew 'cmake'
brew 'xz'
brew 'coreutils'
brew 'ctags'
brew 'git'
brew 'go'
brew 'findutils', args: ['with-default-names']
brew 'libpng'
brew 'freetype'
brew 'openssl'
brew 'gnu-tar'
brew 'gotags'
brew 'libtool'
brew 'htop-osx'
brew 'pkg-config'
brew 'jpeg'
brew 'libtiff'
brew 'imagemagick'
brew 'libevent'
brew 'maven'
brew 'nmap'
brew 'node'
brew 'nvm'
brew 'terraform'
brew 'qt5'
brew 'ruby-build'
brew 'rbenv'
brew 'tmux'
brew 'd12frosted/emacs-plus/emacs-plus', args: ['HEAD', 'with-natural-title-bars']
brew 'vim'
brew 'tmate'
brew 'watch'
brew 'jq'
brew 'jenv'
brew 'openconnect'
brew 'python3'
brew 'adr-tools'
brew 'hub'

cask 'iterm2'
cask 'ngrok'
cask 'virtualbox'

cask 'vagrant'
cask 'docker'

cask 'skype'
cask 'rawtherapee'
cask 'libreoffice'
cask 'google-chrome'
cask 'spectacle'
cask 'android-file-transfer'
cask 'firefoxdeveloperedition'
cask 'flycut'
cask '1password'
cask 'dropbox'
cask 'whatsapp'
cask 'caffeine'
cask 'spotify'
cask 'vlc'
cask 'steam'
cask 'postman'
cask 'keybase'
cask 'intellij-idea-ce'
cask 'slack'
